http:
  host: "0.0.0.0"
  port: "8081"
  path: "![w79ymBxtqL5IqYzcGu9Fkg==]"
db: 
  hostD: "![zbtsInuQD+tGhNFP3lcc8Q7gcbONWGBakAViU2PaAmRpkOczhs4Ldv+BEk7AuMMZ4ioMR6NSaFq1aumkyNp2jw==]"
  portD: "![i2XoqT9ZggsOQbgWi4v57w==]"
  userD: "![FE4xFJfFwp5pUeFq3BMhTw==]"
  passwordD: "![8DjI01PWWMGJl5Dpa/Xlgw==]"
  database: "bank"
email:
  host: "smtp.gmail.com"
  port: "587"
  userE: "![BCWBhvucVCU1IRiMEun0koG9vRE6/CelW9wzZb47/Nw=]"
  passwordE: "![a4rufQ7gOdFi1KGCsMnNrQ==]"
amazon_S3: 
  accessKey: "![hOa+cDC1zdeYh6/VK3Lo+6it9vEkJnJQJyAPuBiT30U=]"
  secretKey: "![Lw9VHhY+HOMFzzgVf0h1j7IPE2PNAmLdKFfpxodg/lMbf+79SYA1neOzdRbFGgPu]"
  region: "US East (N. Virginia)"
api:
  id: "17811017"
profile:
  id: "dev"